# Generated by Django 5.1.5 on 2025-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_post',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news_post',
            name='name',
            field=models.CharField(default='Default Name', max_length=200, verbose_name='Имя автора новости'),
        ),
    ]
